### ISSUE TITLE
highlight default to bold

### ISSUE THREAD

**Issue by tallguyjenks** [Gavinok/ghighlight#1]
used your example code and some python code of my own, and following the syntax:

```groff
.SOURCE python
import urllib2
import re

#connect to a URL
website = urllib2.urlopen(url)

#read html code
html = website.read()

#use re.findall to get all the links
links = re.findall('"((http|ftp)s?://.*?)"', html)

print links
.SOURCE stop
.`` c
#include <stdio.h>
#include <stdlib.h>

int main(int argc, char *argv[])
{
    int i = 0;
    printf("hello\n");
    return 0;
}
.`` stop
```

i get only bold on some keywords:

<img width="889" alt="Screen Shot 2020-08-02 at 7 11 22 PM" src="https://user-images.githubusercontent.com/29872822/89139576-f8879d00-d4f3-11ea-9b2e-5b8d70a27554.png">

i ran `brew install source-highlight` and it installed fine, i have perl 5.30.? not sure why it didnt work

**Comment by tallguyjenks** [comment]
also did execute the command as `ghighlight.pl test.ms | groff -ms -Tpdf > test.pdf` to compile

**Comment by Gavinok** [comment]
I disabled colors for now and use bold until I can resolve some bugs with colors not being properly reset. I haven't gotten a chance to make this optional but hopefully I'll get a chance when I get home.

**Comment by Gavinok** [comment]
@tallguyjenks You can now enable color support by setting GHLENABLECOLOR=1. For more information please check the updated readme.

**Comment by Gavinok** [comment]
the issues are caused by some of the colors used by source-highlight not being defined in groff by default if you want you can define them yourself like so.
```groff
.defcolor darkblue rgb #000999
.defcolor darkred rgb #700000
.defcolor darkgreen rgb #006000
.defcolor darkorange rgb #ff8c00
```
This should define some of the missing colors. feel free to customize I plan to use a system like this for using custom themes.

**Comment by tallguyjenks** [comment]
niiice, i got the color working, now to make gruvbox colors LOL
