### ISSUE TITLE
Respect ".so" Calls

### ISSUE THREAD

**Issue by DSigmund** [Gavinok/ghighlight#3]
In my Project i seperated my text into multiple files and import them using ".so"

Wenn running ghighlight, it does not include the .so files ... could you include this?

**Comment by Gavinok** [comment]
Can you try running it with `soelim` like so

```sh
soelm MAIN.ms | ghighlight | groff -Tpdf > MAIN.pdf
```

This should source the files before running ghighlight.

@DSigmund

**Comment by DSigmund** [comment]
> Can you try running it with `soelim` like so
> 
> ```shell
> soelm MAIN.ms | ghighlight | groff -Tpdf > MAIN.pdf
> ```
> 
> This should source the files before running ghighlight.
> 
> @DSigmund

Many Thanks for the Tipp!
I am very sorry, but, as i am a beginner to groff, i could not find **soelm** anywhere to install or download ...

Any Hint for that?

**Comment by DSigmund** [comment]
The Command is called **soelim** ;-)

And now it works:

`soelim MAIN.ms | ghighlight | groff -Tpdf > MAIN.pdf`

Many Thanks!

**Comment by Gavinok** [comment]
Sorry about the miss spelling wrote that on my phone
